/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package statisticsintegration;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Danielle98
 */
public class Display extends javax.swing.JFrame {
    
    ArrayList frame = new ArrayList();
    int type;
    /**
     * Creates new form Display
     */
    
    public ArrayList disp(ArrayList frame, int type){
        this.frame = frame;
        this.type = type;
        
        String header[] = {"", "","",""};
          DefaultTableModel dtm = (DefaultTableModel) display.getModel();
          System.out.println(frame +"----");
          dtm.setRowCount(frame.size());
          dtm.setColumnCount(4);
          
            for(int i=0;i<display.getColumnCount();i++){
                TableColumn column1 = display.getTableHeader().getColumnModel().getColumn(i);
                column1.setHeaderValue(header[i]);
            }
            
           int ct = 0;
           for (int j = 0; j < frame.size(); j++){
               for(int i = 0; i < 4; i++){
                   if(ct < frame.size()){
                    display.getModel().setValueAt("[Index "+(ct+1)+"]"+frame.get(ct),j,i);
                    ct++;
                   }
               }
           }
           
       return frame;    
    }
    
    
     public ArrayList disp3(ArrayList frame){
        this.frame = frame;
        this.type = type;
        
        String header[] = {"", "","",""};
          DefaultTableModel dtm = (DefaultTableModel) display.getModel();
          System.out.println(frame +"----");
          dtm.setRowCount(frame.size());
          dtm.setColumnCount(4);
          
            for(int i=0;i<display.getColumnCount();i++){
                TableColumn column1 = display.getTableHeader().getColumnModel().getColumn(i);
                column1.setHeaderValue(header[i]);
            }
            
           int ct = 0;
           for (int j = 0; j < frame.size(); j++){
               for(int i = 0; i < 4; i++){
                   if(ct < frame.size()){
                    display.getModel().setValueAt("[Index "+(ct+1)+"]"+frame.get(ct),j,i);
                    ct++;
                   }
               }
           }
      return frame;      
    }
    
    public Display() {
          initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTable();
        hide = new javax.swing.JButton();
        Edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(display);

        hide.setText("Hide Data");
        hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideActionPerformed(evt);
            }
        });

        Edit.setText("Edit Data");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(hide)
                .addGap(74, 74, 74)
                .addComponent(Edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hide)
                    .addComponent(Edit))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_hideActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here
        Integer index = Integer.parseInt(JOptionPane.showInputDialog("Index", null));
        if(type == 2){
        Double newVal = Double.parseDouble(JOptionPane.showInputDialog("New Value", null));
        frame.set(index-1,newVal);
        } else {
        Integer newVal2 = Integer.parseInt(JOptionPane.showInputDialog("New Value", null));    
        frame.set(index-1,newVal2);
        }
        
        
            
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTable display;
    private javax.swing.JButton hide;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
